Removing the 'control.jar' plugin, which is responsible for making the 'Align' submenu appear under the 'Layout' menu in the Cytoscape desktop. This plugin is not working; the following exception appears as output when this menu item is selected:
    java.lang.NoClassDefFoundError: cytoscape/plugin/jar/JarLoader

To resurrect this change you can do the following:

    shell--> cd cytoscape
    shell--> cvs update -j 1.10 -j 1.9 plugins/control.jar
    shell--> cvs update -j 1.3 -j 1.2 plugins/pluginsContents.txt